### ISSUE TITLE
make_slice_voc有问题

### ISSUE THREAD

**Issue by monkeycc** [Zhongyu-Zhang/TIanchi#1]
raw_images_dir='./tile_round1_train_20201231/JPEGImages'
        raw_ann_dir='./tile_round1_train_20201231/Annotations'
        slice_voc_dir = './QG_VOC/Annotations'#切出来的标签也保存为voc格式
        outdir = './QG_VOC/JPEGImages'

Traceback (most recent call last):
  File "g:/Cizhuan/make_slice_voc.py", line 199, in <module>
    slice_im(image_path, ann_path, out_name, outdir, sliceHeight=640, sliceWidth=640)
  File "g:/Cizhuan/make_slice_voc.py", line 171, in slice_im
    make_slice_voc(outpath,exiset_obj_list,sliceHeight,sliceWidth)
  File "g:/Cizhuan/make_slice_voc.py", line 64, in make_slice_voc
    with codecs.open(path_, 'w', 'utf-8') as xml:
  File "D:\anaconda3\envs\lib\codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
OSError: [Errno 22] Invalid argument: './QG_VOC/Annotations/JPEGImages\\0|1024_4096_640_640_0_8192_6000.xml'

**Comment by Zhongyu-Zhang** [comment]
路径报错 改成windows下的路径试试‘//’
